site_name: Adaptive Semantic Judgment Task
site_description: Documentation for Adaptive Semantic Judgement Task
site_url: https://adaptivesemanticjudgementtask.readthedocs.io/
repo_url: https://github.com/DouglasNeuroInformatics/AdaptiveSemanticJudgementTask
repo_name: DouglasNeuroInformatics/AdaptiveSemanticJudgementTask
theme:
  name: material
markdown_extensions:
  - admonition
