import type { WordPairStimulus } from "./schemas";

const stimuliListPractice2 = [
  {
    stimulus: "Wordp2",
    prompt: "Pair1",
    difficultyLevel: 1,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair2",
    difficultyLevel: 2,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair3",
    difficultyLevel: 3,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair4",
    difficultyLevel: 4,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair5",
    difficultyLevel: 5,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair6",
    difficultyLevel: 6,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair7",
    difficultyLevel: 7,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair8",
    difficultyLevel: 8,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Wordp2",
    prompt: "Pair9",
    difficultyLevel: 9,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots1",
    difficultyLevel: 1,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots2",
    difficultyLevel: 2,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots3",
    difficultyLevel: 3,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots4",
    difficultyLevel: 4,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots5",
    difficultyLevel: 5,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots6",
    difficultyLevel: 6,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots7",
    difficultyLevel: 7,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots8",
    difficultyLevel: 8,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire-p2",
    prompt: "de Mots9",
    difficultyLevel: 9,
    language: "fr",
    relation: "unrelated",
  },
] as WordPairStimulus[];

export { stimuliListPractice2 };
