const stimuliList = [
  {
    topStimulus: "Word",
    bottomStimulus: "Pair1",
    difficultyLevel: 1,
    language: "en",
    relation: "related",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair2",
    difficultyLevel: 2,
    language: "en",
    relation: "unrelated",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair3",
    difficultyLevel: 3,
    language: "en",
    relation: "related",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair4",
    difficultyLevel: 4,
    language: "en",
    relation: "unrelated",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair5",
    difficultyLevel: 5,
    language: "en",
    relation: "related",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair6",
    difficultyLevel: 6,
    language: "en",
    relation: "unrelated",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair7",
    difficultyLevel: 7,
    language: "en",
    relation: "related",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair8",
    difficultyLevel: 8,
    language: "en",
    relation: "unrelated",
  },
  {
    topStimulus: "Word",
    bottomStimulus: "Pair9",
    difficultyLevel: 9,
    language: "en",
    relation: "related",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots1",
    difficultyLevel: 1,
    language: "fr",
    relation: "unrelated",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots2",
    difficultyLevel: 2,
    language: "fr",
    relation: "related",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots3",
    difficultyLevel: 3,
    language: "fr",
    relation: "unrelated",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots4",
    difficultyLevel: 4,
    language: "fr",
    relation: "related",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots5",
    difficultyLevel: 5,
    language: "fr",
    relation: "unrelated",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots6",
    difficultyLevel: 6,
    language: "fr",
    relation: "related",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots7",
    difficultyLevel: 7,
    language: "fr",
    relation: "unrelated",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots8",
    difficultyLevel: 8,
    language: "fr",
    relation: "related",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots9",
    difficultyLevel: 9,
    language: "fr",
    relation: "unrelated",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots-1",
    difficultyLevel: -1,
    language: "fr",
    relation: "unrelated",
  },
  {
    topStimulus: "Paire",
    bottomStimulus: "de Mots-2",
    difficultyLevel: -2,
    language: "fr",
    relation: "unrelated",
  },
];

export { stimuliList };
