const stimuliList = [
  {
    stimulus: "Word",
    prompt: "Pair1",
    difficultyLevel: 1,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Word",
    prompt: "Pair2",
    difficultyLevel: 2,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Word",
    prompt: "Pair3",
    difficultyLevel: 3,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Word",
    prompt: "Pair4",
    difficultyLevel: 4,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Word",
    prompt: "Pair5",
    difficultyLevel: 5,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Word",
    prompt: "Pair6",
    difficultyLevel: 6,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Word",
    prompt: "Pair7",
    difficultyLevel: 7,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Word",
    prompt: "Pair8",
    difficultyLevel: 8,
    language: "en",
    relation: "unrelated",
  },
  {
    stimulus: "Word",
    prompt: "Pair9",
    difficultyLevel: 9,
    language: "en",
    relation: "related",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots1",
    difficultyLevel: 1,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots2",
    difficultyLevel: 2,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots3",
    difficultyLevel: 3,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots4",
    difficultyLevel: 4,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots5",
    difficultyLevel: 5,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots6",
    difficultyLevel: 6,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots7",
    difficultyLevel: 7,
    language: "fr",
    relation: "unrelated",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots8",
    difficultyLevel: 8,
    language: "fr",
    relation: "related",
  },
  {
    stimulus: "Paire",
    prompt: "de Mots9",
    difficultyLevel: 9,
    language: "fr",
    relation: "unrelated",
  },
];

export { stimuliList };
